import { Router } from 'express';
import { getUsers, getUserById, updateUser, deactivateUser } from '../controllers/user.controller';
import { authenticate, authorize, requireAdmin } from '../middleware';
import { UserRole } from '../types';
const router = Router();
router.get('/', authenticate, authorize(UserRole.ADMIN, UserRole.PROJECT_MANAGER, UserRole.INSPECTOR), getUsers);
router.get('/:id', authenticate, requireAdmin(), getUserById);
router.patch('/:id', authenticate, requireAdmin(), updateUser);
router.delete('/:id', authenticate, requireAdmin(), deactivateUser);
export default router;
